[package]
name = "wdm-gtk-greeter"
description = "GTK4 greeter for wdm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wdm-greeter-client.workspace = true
gtk4.workspace = true
gtk4-layer-shell.workspace = true
env_logger.workspace = true
log.workspace = true
