[workspace]
resolver = "3"
members = [
    "crates/wdm-protocol",
    "crates/wdm",
    "crates/wdm-greeter",
    "crates/wdm-gtk-greeter",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
wdm-protocol = { path = "crates/wdm-protocol", version = "0.1.0" }

wayland-server = "0.31"
wayland-client = "0.31"
wayland-scanner = "0.31"
wayland-protocols = "0.32"
wayland-protocols-wlr = "0.3"

thiserror = "2"
log = "0.4"
