#!/usr/bin/env bash
#
# Regenerates everything under vendor/.
#
# The theme ships its vendor/ directory checked in, so this script is not part
# of any build — installing the theme copies files and runs nothing. It exists
# so that "where did vendor/tailwind.css come from" has an answer that is a
# command rather than a memory, and so that bumping Tailwind or Font Awesome is
# one run rather than a hand-edit of a generated file.
#
# Needs npm and a network. Run it from this directory.
set -euo pipefail

cd "$(dirname "$0")"
here=$(pwd)

# Pinned, not floating. A theme whose appearance depends on whatever the
# registry served that morning is a theme nobody can reproduce a bug in.
TAILWIND_VERSION=4.3.3
FONTAWESOME_VERSION=7.3.1

# The icons index.html actually uses. Every one costs a rule in the generated
# stylesheet and nothing else — the font file is shipped whole, because Font
# Awesome does not publish a subsetter and one that lived here would be a
# second thing to get wrong.
ICONS=(clock user lock display arrow-right-to-bracket)

work=$(mktemp -d)
# The symlink goes too. `@import "tailwindcss"` is resolved by walking up from
# the input file, so the packages have to be reachable from inside the theme
# for the duration of the build — and must not be left there afterwards, since
# a node_modules in a theme directory would be copied by the install rules.
trap 'rm -rf "$work"; rm -f "$here/node_modules"' EXIT

echo "==> installing tailwindcss@$TAILWIND_VERSION, fontawesome@$FONTAWESOME_VERSION"
cd "$work"
npm init -y > /dev/null
npm install --silent \
  "tailwindcss@$TAILWIND_VERSION" \
  "@tailwindcss/cli@$TAILWIND_VERSION" \
  "@fortawesome/fontawesome-free@$FONTAWESOME_VERSION"

fa=$work/node_modules/@fortawesome/fontawesome-free

mkdir -p "$here/vendor"

echo "==> building vendor/tailwind.css"
# --minify because this file is read by a browser, never by a person; src/
# input.css is the readable half. Run from $here so @source's relative paths
# resolve against the theme rather than the temporary directory — and invoke
# the binary by path rather than through npx, which resolves against the
# current directory and so would look for it under the theme.
ln -sfn "$work/node_modules" "$here/node_modules"
(cd "$here" && "$work/node_modules/.bin/tailwindcss" \
  -i src/input.css \
  -o vendor/tailwind.css \
  --minify)

echo "==> building vendor/fontawesome.css"
# Generated from the upstream stylesheet rather than transcribed from it: the
# codepoints are read out of the package, so a Font Awesome release that moves
# an icon changes this file the next time the script runs instead of leaving a
# stale literal behind that renders as a blank box.
python3 - "$fa" "$here/vendor/fontawesome.css" "$FONTAWESOME_VERSION" "${ICONS[@]}" <<'PYTHON'
import re
import sys

fa_dir, out_path, version, *icons = sys.argv[1:]
source = open(f"{fa_dir}/css/all.css").read()

rules = []
for name in icons:
    match = re.search(r"\.fa-" + re.escape(name) + r"\s*\{\s*--fa:\s*(\"[^\"]*\")", source)
    if not match:
        sys.exit(f"fa-{name} not found in Font Awesome {version} — was it renamed?")
    rules.append(f'.fa-{name} {{ --fa: {match.group(1)}; }}')

open(out_path, "w").write(f"""/*
 * Font Awesome Free {version} — the subset this theme uses.
 *
 * GENERATED by build.sh. Do not edit; edit ICONS there and re-run.
 *
 * Upstream's all.css is ~127 KB and defines every icon in the free set. A
 * login screen uses {len(icons)}, so this carries {len(icons)} rules and the base
 * rendering rules they need. The font file is shipped whole — Font Awesome
 * publishes no subsetter, and one written here would be another thing that
 * can be wrong in a way you only see on the screen you cannot log in from.
 *
 * Icons: CC BY 4.0. Fonts: SIL OFL 1.1. Code: MIT.
 * https://fontawesome.com/license/free — see LICENSE-fontawesome.txt.
 */
@font-face {{
  font-family: "Font Awesome 7 Free";
  font-style: normal;
  font-weight: 900;
  /* block, not swap: the fallback for a missing glyph is a tofu box, and a
     login screen briefly showing boxes where its icons go reads as broken. */
  font-display: block;
  src: url("fa-solid-900.woff2") format("woff2");
}}

.fa-solid {{
  --fa-style: 900;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: var(--fa-display, inline-block);
  font-family: "Font Awesome 7 Free";
  font-style: normal;
  font-synthesis: none;
  font-variant: normal;
  font-weight: 900;
  line-height: 1;
  text-align: center;
  text-rendering: auto;
  width: var(--fa-width, 1.25em);
}}

/* The alternative-text form; WebKit supports it, and the plain fallback below
   is what upstream ships for engines that do not. */
.fa-solid::before {{
  content: var(--fa)/"";
}}

@supports not (content: ""/"") {{
  .fa-solid::before {{
    content: var(--fa);
  }}
}}

{chr(10).join(rules)}
""")
print(f"    {len(icons)} icons")
PYTHON

echo "==> copying vendor/fa-solid-900.woff2"
cp "$fa/webfonts/fa-solid-900.woff2" "$here/vendor/fa-solid-900.woff2"

echo "==> vendoring vendor/archlinux-logo.svg"
# The official mark, not a redrawing of it. On Arch it is shipped by
# `filesystem`, which is a mandatory package, so the authoritative copy is
# already on any machine that can run this script; elsewhere the same file is
# pulled out of that package from a mirror.
#
# Verified either way. A logo taken from whatever happened to be on the build
# machine is a logo nobody can confirm is the real one, and this is the single
# asset in the theme that carries somebody else's trademark.
ARCHLINUX_LOGO_SHA256=3ffe8ea4e98db43a3ec4dcca55fd4009cd8b8d220f0996aef7a5b427fdf65234
system_logo=/usr/share/pixmaps/archlinux-logo.svg

if [[ -f $system_logo ]]; then
  echo "    from $system_logo"
  cp "$system_logo" "$work/archlinux-logo.svg"
else
  echo "    not an Arch machine; fetching the filesystem package"
  mirror=https://geo.mirror.pkgbuild.com/core/os/x86_64
  package=$(curl -sfL "$mirror/" | grep -o 'filesystem-[0-9][^"]*-any\.pkg\.tar\.zst' | sort -u | tail -1)
  [[ -n $package ]] || { echo "could not find the filesystem package on $mirror" >&2; exit 1; }
  curl -sfL -o "$work/filesystem.pkg.tar.zst" "$mirror/$package"
  tar -x -C "$work" -f "$work/filesystem.pkg.tar.zst" usr/share/pixmaps/archlinux-logo.svg
  mv "$work/usr/share/pixmaps/archlinux-logo.svg" "$work/archlinux-logo.svg"
fi

echo "$ARCHLINUX_LOGO_SHA256  $work/archlinux-logo.svg" | sha256sum --check --status || {
  echo "archlinux-logo.svg does not match the pinned checksum — upstream changed" >&2
  echo "the artwork, or the copy on this machine is not the distribution's." >&2
  echo "Confirm the new file is genuine, then update ARCHLINUX_LOGO_SHA256." >&2
  exit 1
}
cp "$work/archlinux-logo.svg" "$here/vendor/archlinux-logo.svg"

echo "==> copying licences"
cp "$fa/LICENSE.txt" "$here/vendor/LICENSE-fontawesome.txt"
cp "$work/node_modules/tailwindcss/LICENSE" "$here/vendor/LICENSE-tailwind.txt"
# Shipped beside the logo because the logo is a trademark, not a licence-free
# asset: this is the notice Arch itself ships in /usr/share/licenses.
cat > "$here/vendor/TRADEMARKS-archlinux.txt" <<'NOTICE'
The ARCHLINUX name and logo are recognized trademarks.
See http://www.archlinux.org/ for acceptable use and restrictions.
NOTICE

echo
echo "done. vendor/ is:"
ls -la "$here/vendor"
